create table roles
(
    name varchar(255) not null,
    primary key (name)
);

create table users
(
    id       int8 generated by default as identity,
    email    varchar(255) not null,
    password varchar(255) not null,
    primary key (id)
);

create table users_roles
(
    id   int8         not null,
    name varchar(255) not null
);

alter table if exists users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table if exists users_roles add constraint FK8etuiwnraq2fv8ayks3mavouu foreign key (name) references roles on delete cascade;
alter table if exists users_roles add constraint FKcndc1cly4axcyqvgxn0x9xjxm foreign key (id) references users on delete cascade;

insert into roles VALUES ('USER_ROLE'), ('ADMIN_ROLE'), ('MANAGER_ROLE')