create table categories
(
    id    int8 generated by default as identity,
    title varchar(255),
    primary key (id)
);
create table products
(
    id    int8 generated by default as identity,
    img oid,
    price numeric(19, 2),
    title varchar(255),
    primary key (id)
);
create table products_categories
(
    product_id  int8 not null,
    category_id int8 not null
);
alter table if exists products_categories add constraint FKqt6m2o5dly3luqcm00f5t4h2p foreign key (category_id) references categories;
alter table if exists products_categories add constraint FKtj1vdea8qwerbjqie4xldl1el foreign key (product_id) references products;

insert into categories(title) values
    ('man'),
    ('women'),
    ('children');

insert into products(price, title) values
    (2000, 'T-shirt child'),
    (3500, 'T-shirt man'),
    (3500, 'T-shirt woman'),
    (8000, 'sleeper child'),
    (1500, 'sleeper man'),
    (6500, 'sleeper woman'),
    (8800, 'bodysuit child'),
    (6600, 'bodysuit man'),
    (20000, 'bodysuit woman');

insert into products_categories values
    (2,1),
    (5,1),
    (8,1),
    (3,2),
    (6,2),
    (9,2),
    (1,3),
    (4,3),
    (7,3)